apiVersion: v1
kind: Secret
metadata:
    name: sehstudents-db-secret
    namespace: sehsitin
type: Opaque
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:iPI+iKloJ9hw,iv:lwqtBtaXxVkmL9jf+4idnDaUmvAfNSqMhj8zuNWKi1M=,tag:D2Di8gZR2wyel1QEkEoFiw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:Ei+H5X1l4LYMyYvt/Q==,iv:oXxhcuSPSMnAUTL1UkSDN5rgatbkLs1oRfngpwDGEuA=,tag:andoJLYfJS/wGLPpNCAoRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHdWtqNWNhd3RDWEFTa0VM
            WDlmUUs1OVlxVGplT3VlTzI1Tmhxejc4UVJNCmliQjNNNEhkTFhHVktXQ2lZU3JH
            RWtJcUNLaG53eDVJekcyQSsrZVBvb28KLS0tIEFxWjhBMnRzWDcvbUVGeE41TlVW
            Vk9YVjFpS0RsbEJIWjZDYWVIODhBL1kKKnwWH90FSZQE7mazLxkYGqxDBLLPwjxx
            GKL5w1n98ggIzEKq9mV+CUsxAi4ReRlGrMU9QtWvznoF3HD+c3OaaA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjhjzmsqcpthw6nhq5g5cdr9juvf7pqgjlqd0nt96sw2wfmwcvlswcz29d
    encrypted_regex: ^(data)$
    lastmodified: "2026-08-03T07:10:50Z"
    mac: ENC[AES256_GCM,data:9cdIXIVXKqWZR+mXx6yvNppO7yTsrVRqYhEy2WTwEJ+nmNa8GAIZM+Na0oqsFQJtAhC8XDxc9zJ83ps09e4YCoWeBXRsZsDPR2INOud3sG75ui5o8gYuMZ4AyxKjsPrV2845Kt4le8NgcO+ZkkiiR2Yfw5eFXuhUyNzaCkz5bdM=,iv:HEe4QhLG1wLG8zeb/+MJALuHsKItfI+y5mMKomlkNmA=,tag:q8XLGkaDdronLGwsa9pQEw==,type:str]
    version: 3.13.3
