apiVersion: v1
kind: Service
metadata:
  name: seh-backend-svc
  namespace: sehsitin
spec:
  ports: 
  - name: application
    port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    app: seh-students