apiVersion: apps/v1
kind: Secret
metadata:
    name: sehstudents-db-secret
    namespace: sehsitin
type: Opaque
data:
    DB_USERNAME: ENC[AES256_GCM,data:A/DwuNx0cFI8,iv:/tFNiQeHyMfp7rydiWrAnufeA0mSc34vGz+3WenH1wk=,tag:YyraXRckgIWo7tRHvF3W3A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:tWjlElcEHpjcgIrhOA==,iv:65OXCuuuuBByyLcIyDsbVp81sAuSgEK+D4HQNjMydPY=,tag:ipIWBJ/SM4E4OVuLWll71Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdGFabWlQYkFCRlVWL0dG
            alBHR0ZrWkp2U0VBczA0NzFudlMvMDd5L1JRClVLbHFaRFNJMnJjMlBiN1pheG1m
            RkRUVm1MaGk5SEQ4a01TbkVWMHl5T00KLS0tIENiRXhZNFVudUh6dWJNdVlXbzY1
            L1lOMVFxZVpIRjNaK2hiQitUekpVRzQKVS5/aAXliUwyKfQyMTIzswJ3yonym2lR
            IzKtbAdpG4UaIwGp9iiNpcWRONN1EjqKVzNJTGZ+T7BOz7LpPePRfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjhjzmsqcpthw6nhq5g5cdr9juvf7pqgjlqd0nt96sw2wfmwcvlswcz29d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T07:16:06Z"
    mac: ENC[AES256_GCM,data:SRvaPvaL+J/gIQ/Cw7DFaZ5agMTGGhX+3fVGr1XWcbmOh3OhCCU6V8ePxrrUMSgG33zZU5bYdiflDKYf0F/vIWOsndFfAjcuXVH6UlW5uSt0CMYD5LM1aVEJmyZp6Xlci4fUHAJBKqWS1o82ai4PqDrEJUqMXDSQudEnfMTvei8=,iv:spMa+DIXs8ZJhVXOUOhk/BtRMKf4zw6dOEXomv36CUM=,tag:xl7oplIJrpoywhLWNC/ujQ==,type:str]
    version: 3.13.3
