apiVersion: v1
kind: Secret
metadata:
    name: sehstudents-db-secret
    namespace: sehsitin
type: Opaque
data:
    DB_USERNAME: ENC[AES256_GCM,data:tjAibAvN3o5h,iv:cCPezfywyx9/6NS4PffVxuil4mj+pCAhuvKT92lybY0=,tag:dgJtH4YmjwkyUb7ioKtKOA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:gC9KTu8ia+CBYBdjgQ==,iv:IrUhtGjlmaTDdxELNQMmoR8vLm+DEvbQHxRN1V+OHcc=,tag:Qq2MgL2wiUM4TRaj9GlzEA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEY0FuckYrc3lBT3lPSEV0
            SSthaW5sM3hYUDgyanhac1pFdkl5Mjd5dDBzCm15ZGZmM0xaZEFyVVFnT0xXbWE2
            a1ZOUnFTNXhnblZuK1V4a1RscWZPSXcKLS0tIEdHRFhVNEVPN25NdG1RM0lLbXRR
            T3JraGN2YXRQVHBuSDFIYXg0NWFFSVEKoCP54UctfMyLAAOaDiReAXIaE+aGL32G
            mtYhvxI6XfLQz6iYOFb60Nf8FBbEyRcvUvlrQ81+JnUhJNjv5nrfmg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kjhjzmsqcpthw6nhq5g5cdr9juvf7pqgjlqd0nt96sw2wfmwcvlswcz29d
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-16T07:24:14Z"
    mac: ENC[AES256_GCM,data:ENDndLAiMLzqhAyU6NIHPByqmxv9Saf6+OL3UfA4DQZKxgyTgVX07vRLHp/44vTATC7lH192/npxSQ5/SksaAqyoRI/62EeppgrYQvLj30pnLg+nuls3QuI7xStGyw1yT7H8+EDtZ8ITkSdFtmFUcKf2aa6c3fvxzrrB3MZemYo=,iv:PGtrd6COAiAP/8fswuRpxOUd1Y0ISyI+uIIRDTu8sMQ=,tag:XpftKTgDPqz5TrOCidhtUA==,type:str]
    version: 3.13.3
