apiVersion: v1
kind: Service
metadata:
  name: sehstudents-svc
  namespace: sehsit
spec:
  ports: 
  - name: application
    port: 3000
    targetPort: 3000
  type: ClusterIP
  selector:
    type: seh-backend